# Generated by Django 4.2.5 on 2023-09-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=128)),
                ('Lname', models.CharField(max_length=128)),
                ('User_Name', models.CharField(max_length=128)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
