# Generated by Django 4.2.5 on 2023-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=128)),
                ('Code', models.IntegerField(max_length=5)),
                ('Author_Name', models.CharField(max_length=128)),
                ('Status', models.CharField(max_length=128)),
                ('Amount', models.IntegerField()),
                ('Created_date', models.DateField()),
                ('Updated_date', models.DateField()),
            ],
        ),
    ]
